### ISSUE TITLE
FR: Use zram / zswap rather than a swap file

### ISSUE THREAD

**Issue by samip5** [CryoByte33/steam-deck-utilities#10]
"The [zram](https://docs.kernel.org/admin-guide/blockdev/zram.html) kernel module (previously called compcache) provides a compressed block device in RAM. If you use it as swap device, the RAM can hold much more information but uses more CPU. Still, it is much quicker than swapping to a hard drive. If a system often falls back to swap, this could improve responsiveness. Using zram is also a good way to reduce disk read/write cycles due to swap on SSDs."

https://wiki.archlinux.org/title/improving_performance#zram_or_zswap

**Comment by phush0** [comment]
zswap is enabled by default in arch kernel and its purpose is to have compressed cache of the pages in swap file, so nothing to do here. zram is a compressed swap file in memory and it's efficiency depends on how good can you compress data that have to go in swap.

**Comment by CryoByte33** [comment]
I've tested ZRAM fairly extensively. Its performance tends to be slightly worse (~5%) to identical to the swap file, and also brings other complications along like needing to permanently block VRAM expansion past a certain point, or only using 8GB of ZRAM which has negative performance implications.

I plan on having an option to use ZRAM instead of swap eventually, but my recommendation will still be to use swap primarily as the performance is better and SSD wear impact is negligible with the swappiness tuned low.

Please feel free to re-open this if you disagree!

**Comment by lordkitsuna** [comment]
> I've tested ZRAM fairly extensively. Its performance tends to be slightly worse (~5%) to identical to the swap file, and also brings other complications along like needing to permanently block VRAM expansion past a certain point, or only using 8GB of ZRAM which has negative performance implications.
> 
> I plan on having an option to use ZRAM instead of swap eventually, but my recommendation will still be to use swap primarily as the performance is better and SSD wear impact is negligible with the swappiness tuned low.
> 
> Please feel free to re-open this if you disagree!

hey i wanted to bring this back up. i have been doing some testing and i have found that, when using the lz4 algorithm in particular, performance seems to be slightly better than swap alone. My testing is a fairly limited set of games mind you so i am not willing to call it meaningful data. was curious if when putting zram through its paces you tried lz4 over zstd. 

its my understanding that lz4 is both lighter on cpu and lower latency than zstd even with zram so this may be why it ended up not having that 5% you saw but it could also just be i don't have a large enough test case. I also set vm.page-cluster=1to further reduce latency which may have helped as well.

**Comment by lordkitsuna** [comment]
> I actually followed all of the arch wiki's recommendations as you did during all of my testing, which took place during every "Deck Dive". I am interested in your results as I've noticed results within margin of error to swap across the board until memory exhaustion, though 🤔

it's the lz4 algorithm I'm most interested in if you tried or not. default is zstd but I've found multiple tests that show lz4 to be faster in both bandwidth and latency at the cost of some ratio. it may be the difference needed. or maybe my test games are just lucky and have highly compressible data lol

**Comment by CryoByte33** [comment]
Yes, I've tried lz4, deflate, zstd and lzo.

**Comment by lordkitsuna** [comment]
very strange, I'll try to do a deeper dive and see if I can get actual hard graphs/numbers on anything

**Comment by CryoByte33** [comment]
It's possible that kernel or amdgpu updates have lead to different behavior in recent months, I plan to go through an extensive retesting effort once SteamOS 3.5 releases.
