### ISSUE TITLE
Pumkin Jack Drops to 7 fps after change

### ISSUE THREAD

**Issue by Benjamin-Berger** [CryoByte33/steam-deck-utilities#107]
Loads like normal at 60 fps but as soon as it gets into the title screen it drops to 6-8fps.

First game run after installing CyroByte utilities. 

Other games seem to be running file

**Comment by CryoByte33** [comment]
A few quick questions:
1. Have you rebooted since applying the changes?
2. Are you using all the recommended settings?
3. Did you "sync" the data to another storage location?

**Comment by Benjamin-Berger** [comment]
Woah amazingly fast reply! 

I have rebooted, as I set the frame buffer size to 4gb. 

As I installed a 1tb hard drive, I set the swap file size to 32 gb. 

Nope didn't do the sync :) as I mentioned with the 1tb hard drive im happy to have the shaders stored internally. 

Another game I found this for was with Journey to the Savage Planet, the frames dropped down to 15fps

**Comment by CryoByte33** [comment]
Very interesting, are they all very consistent results? 

Also, do the results get better if you set the UMA frame buffer back to 1GB? I'm wondering if there's just not enough fast memory for these games in particular 🤔

**Comment by Benjamin-Berger** [comment]
...Turning it off and on again seemed to fix the issue. 

Closing the issue, thank you for the amazing responses. You're incredible! Buying you a coffee
