### ISSUE TITLE
TRIM might need to be removed or test if it is enabled already

### ISSUE THREAD

**Issue by markstinson** [CryoByte33/steam-deck-utilities#11]
https://steamcommunity.com/app/1675200/discussions/0/5568165891217929856/

The new 3.4 beta notes state that Valve is re-instating TRIM for both internal storage AND only those SD cards with stated support.

It might be worthwhile to either have the steam-deck-utilities verify that TRIM is already enabled and present an appropriate recommendation.

**Comment by CryoByte33** [comment]
I'll be disabling my TRIM-on-schedule automatically in a script update coming very soon, but leaving TRIM-on-demand since I still think it's useful in situations where you recently deleted a lot of data. Keep an eye out!

**Comment by CryoByte33** [comment]
Update: This has been fixed with the [latest commit](https://github.com/CryoByte33/steam-deck-utilities/commit/984dcdcd251fae838217f8a476f8852bfa352f25). Closing this issue 🙂
