### ISSUE TITLE
Small windows size (UI) bug

### ISSUE THREAD

**Issue by Najimaru76** [CryoByte33/steam-deck-utilities#110]
Hello,

When I updated to the last version, the windows screen of Cryoutilities is very small.
I can't resize it either.
Tried to uninstall and install it back, same issue (with and without an external screen).

![Cryoutilities ui size bug](https://user-images.githubusercontent.com/118555127/224716813-ce0457f8-a573-40ed-a814-6212e1ab4261.png)

Best regards

**Comment by Najimaru76** [comment]
[cryoutilities.log](https://github.com/CryoByte33/steam-deck-utilities/files/10958027/cryoutilities.log)

I added the log file :)

**Comment by ElNovi** [comment]
Hi, can you please post the Display settings screen?

**Comment by Najimaru76** [comment]
> Hi, can you please post the Display settings screen?

sure.

![Screenshot_20230313_181038](https://user-images.githubusercontent.com/118555127/224775306-2ef88809-60ac-41dd-b30d-4cbf49c74016.png)

Many thanks

**Comment by ElNovi** [comment]
Seems like you have more then one monitor and this one is not your primary - we scale the app based on primary monitor

Can you please write to Konsole `xrandr -q` and paste the output here?

**Comment by Najimaru76** [comment]
Hello,

here's the output:

> (deck@Deck-Naj ~)$ xrandr -q
Screen 0: minimum 320 x 200, current 1280 x 800, maximum 16384 x 16384
eDP connected (normal left inverted right x axis y axis)
   800x1280      60.00 +
   800x600       60.00  
   640x480       60.00  
DisplayPort-0 connected primary 1280x800+0+0 (normal left inverted right x axis y axis) 597mm x 336mm
   3840x2160     60.00 +  60.00    50.00    59.94    30.00    29.97    24.00  
   2560x1440     59.95  
   1920x1200     59.95  
   1920x1080     60.00    60.00    50.00    59.94  
   1600x1200     60.00  
   1680x1050     59.88  
   1600x900      60.00  
   1280x1024     60.02  
   1440x900      59.90  
   1280x800      60.00* 
   1280x720      60.00    50.00    59.94  
   1024x768      60.00  
   800x600       60.32  
   720x576       50.00  
   720x480       60.00    59.94  
   640x480       60.00    59.94  
   720x400       70.08  
(deck@Deck-Naj ~)$ 


I have an external screen, but I only use one at time. I don't use dual display.
And even with my monitor, I still use the native resolution of the Deck 1280x800 (in portrait).
Another thing I just found out: if I hot unplug my hdmi cable. 
The UI of CryoUtilities is back to normal on the Deck screen...

Thanks.

**Comment by ElNovi** [comment]
Can you please update the CryoUtilities and post the content of cryoutilities.log file after you encounter the issue again? I added logs for scalling issues in https://github.com/CryoByte33/steam-deck-utilities/pull/112

**Comment by Najimaru76** [comment]
Hello,

Sorry was busy yesterday.
Did the update, and here is the log:

>
INFO	2023/03/15 11:39:56 Current Version: 2.1.4
INFO	2023/03/15 11:39:56 Setting scale 0.250000

thanks again :)

**Comment by ElNovi** [comment]
> Hello,
> 
> Sorry was busy yesterday. Did the update, and here is the log:
> 
> > 
> 
> INFO 2023/03/15 11:39:56 Current Version: 2.1.4 INFO 2023/03/15 11:39:56 Setting scale 0.250000
> 
> thanks again :)

That's really strange, the scalling is set to 0,25 which is ok for 1280x800. Can you disable/disconnect all the other monitors so xrandr shows only the Steam Deck one and then try again? I guess that Fyne get's somehow crazy with your setup and missiterprets the scalling.

**Comment by Najimaru76** [comment]
Hi again,

So I did more testing. I can't reproduce the bug with the Deck screen. UI size is now correct in handled mode.

But with an external monitor:

With a 4K resolution, the window scale is OK:
![Screenshot_20230315_153507 4K](https://user-images.githubusercontent.com/118555127/225344690-c47d61f4-e10e-48b1-9fac-e2fe85073f0d.png)

But with a 1280x800 resolution (like the Deck screen), I still have the issue:

![Screenshot_20230315_153630 1280x800](https://user-images.githubusercontent.com/118555127/225345044-190f0727-537e-448c-8452-1517badba64e.png)

If you wonder why I don't use 4K resolution with my monitor, it's mainly for configuring non steam games in desktop mode. 
For example, it allow me to setup my emulators with the right aspect ratio and shaders (like scanlines and filters).
And for non steam games, or the ones that are not "supported"  by Valve, to tweak them correctly.

But I used the CryoUtilities ver 2.0, and had no scaling issue... strange.
I guess I'll have to switch back to 4K just for updating your great tool. It's not like I'm doing it everyday :)

Thanks again for your hard work.

Feel free to ask me to do more testings.

**Comment by TheKerevas** [comment]
I have the same problem but with 1080p monitor, I didn't have this problem before. Using only Steam Deck everything works, or putting the resolution 1920x1080 on the monitor

**Comment by ElNovi** [comment]
I think i figured out what is happening, if anyone could test my pull request, it would be great :) - https://github.com/CryoByte33/steam-deck-utilities/pull/115

**Comment by ElNovi** [comment]
Well compiling on the Steam Deck is not trivial, maybe i could send you the binary if you are on the Cryo's Discord server or i can test it myself tonight.

**Comment by Najimaru76** [comment]
![Cryoutilities 115 pull request 1280x800](https://user-images.githubusercontent.com/118555127/225669163-04c2cd4d-48d3-4bea-afd6-854fecbca563.png)

No change :'(

**Comment by ElNovi** [comment]
4K TV with 4K resolution
![PXL_20230316_170929211 NIGHT](https://user-images.githubusercontent.com/14199592/225885679-38d1cb0f-c99a-4a77-8683-293911cebb27.jpg)

4K TV with 1280x800
![PXL_20230316_170809277 NIGHT](https://user-images.githubusercontent.com/14199592/225885689-088c93c9-b005-4b09-b04c-ddb2cb2059ca.jpg)

Maybe i sent you wrong binary 😓

**Comment by TheKerevas** [comment]
Still no fix? :(

**Comment by JSaterdalen** [comment]
This is happening to me on the Steam Deck OLED. I have never connected it to an external display.

**Comment by tyvsmith** [comment]
Seeing the same. The steamdeck Oled has this experience out of the box on the native display without ever being connected to an external monitor.

**Comment by f3bandit** [comment]
oled same here

**Comment by CryoByte33** [comment]
I just received my OLED, I'll try testing this in a few days. That said, Fyne isn't making this easy at all and I'm not sure if I'll be able to fix it without substantial effort/rework, or maybe completely changing the GUI library.

I'll update here when I know what's what!

**Comment by elusiveaura** [comment]
Following for updates. Same issue on my OLED

**Comment by KrisieP** [comment]
I'm also experiencing this issue on my 512 oled

**Comment by SamueleLorefice** [comment]
Dunno if I should open a separate issue or not, but I'm having the opposite problem on my deck, after having installed DeckHD screen replacement (bumping resolution to 1920x1200), the window is now bigger than the screen and is not resizable.

![image](https://github.com/CryoByte33/steam-deck-utilities/assets/6562494/35a91c54-e939-4f9c-b281-38604681d225)

**Comment by CryoByte33** [comment]
The issue is just that the GUI framework doesn't allow resizing at all, so this is less a bug with CU and more a limitation of Fyne. 
The entire point of the launcher in CU is to mitigate the issue, but we may be approaching the point of a major refactor using a different framework if these issues are gonna keep popping up with every new screen 😓

**Comment by SamueleLorefice** [comment]
But is this a problem with resizing the actual single UI elements or just the window? Because it would be fine if the window would be a set pixel size. (I dunno how this framework works). Like, my issue in particular is that somehow the window is shbowing at an insane size even if the screen is still larger. Would it be possible to not have the window size scalable at all and just have the window come up as 1280x720 so that it displays fine on a basic steamdeck, fine aswell on a DeckHD and still readable in an external screen?

**Comment by CryoByte33** [comment]
> But is this a problem with resizing the actual single UI elements or just the window? Because it would be fine if the window would be a set pixel size. (I dunno how this framework works). Like, my issue in particular is that somehow the window is showing up at an insane size even if the screen is still larger (than a stock steamdeck). Would it be possible to not have the window size to scale at all based on the display and just have the window come up as 1280x720 so that it displays fine on a basic steamdeck, fine aswell on a DeckHD and still readable in an external screen?

In Fyne, windows cannot be resized at all. That necessitates me setting the "Scaling" on launch, but it's incredibly inconsistent across screens, since it's a relative value based on what Fyne thinks should be the size. In addition, it hates portrait displays so the scaling is completely different on internal and external displays. We've had dozens of commits trying to fix it, but the framework is just not designed for this use case and is very opinionated in how it scales.

**Comment by CryoByte33** [comment]
Small update to this: The previous method of setting a scale (FYNE_SCALE=) seems to just... not work anymore, despite it still being the preferred method in the documentation.

I'll be investigating more over the weekend, and will open a bug report with Fyne if I can't determine a better solution.

**Comment by MisterFloppy** [comment]
I Just updated to v2.2.2 and the issue started happening on my Steam Deck for the first time, please fix the bug!
