### ISSUE TITLE
binary panics on missing /root/.cryo_utilities

### ISSUE THREAD

**Issue by gitsmol** [CryoByte33/steam-deck-utilities#117]
Because i don't intend to use the GUI I just downloaded the binary and ran it with sudo (as recommended):
`NOTE: You NEED to run this with sudo if not using GUI mode.`

It panics:
`panic: open /root/.cryo_utilities/cryoutilities.log: no such file or directory`

There seems to be a mechanism in place to replace the logfile on every run:
```
// Delete old log file
	os.Remove(internal.LogFilePath)
	// Create a log file
	logFile, err := os.OpenFile(internal.LogFilePath, os.O_RDWR|os.O_CREATE, 0666)
	if err != nil {
		log.Panic(err)
	}
	defer logFile.Close()
	log.SetOutput(logFile)
```
But this probably doesn't work when the parent directory for the log file is not there. I've little experience with Go but I assume os.OpenFile doesn't create the parent directory and just panics when it isn't there.

One might consider not logging in the root dir but incorporating sudo or doas in the Go program. That way you log where the user expects the log to go and you don't have to create data in the root homedir. A little work, of course, but a lot cleaner imho. I could try to make a PR for this myself over the weekend and see how it fares.

A simpler option would be to log to stdout instead of panicking. 

(Besides this minor nitpick, the performance difference these tweaks make is incredible. A memory heavy game like CoD MW Remastered goes from stuttering to buttery smooth.)

**Comment by CryoByte33** [comment]
Ah, yeah so I intend for installation to be done regardless of how you intend to run it. I actually had it create the parent directory in the beta, but there was a bug when doing so where the directory wouldn't be writable until the next run.

As for running sudo in the program, this was also in the original version, but I couldn't find an easy way to intake the sudo password safely.

For example, taking the sudo password as a flag makes it visible in plaintext, so I'd need to force a interactive CLI interface. I could do this, but then the uninstaller couldn't be run as a simple "revert to stick" without having the user use the CLI, which is too complicated for many users.

If you have a way to mitigate all of these problems, I'm definitely happy to hear it, but the simplest I came up with was running with sudo itself and letting PAM deal with authentication 🙂

**Comment by gitsmol** [comment]
Seems like you're three steps ahead of me :)

For the CLI, relying on the user to handle privileges is a very safe solution, I agree. Right now this path is a little rocky, however, because neither the installer nor the program addresses the problem of the /root/.cryo_utilities directory being missing. Without asking for privileges the installer can't create the necessary directory. When running with elevated privileges the program doesn't create the necessary directory. 

So i'd say try to create the directory if it isn't there (since user has already elevated privileges at that point) and fall back to logging to stdout if that doesn't work for some reason. Unless you feel not being able to log to the dir of choice might reasonably precede some kind of other failure.

> For example, taking the sudo password as a flag makes it visible in plaintext, so I'd need to force a interactive CLI interface. I could do this, but then the uninstaller couldn't be run as a simple "revert to stick" without having the user use the CLI, which is too complicated for many users.

I don't think I understand this one. If I need root privileges to make the suggested changes, wouldn't I also need root to revert them?

**Comment by gitsmol** [comment]
Ah, I see. 

> For this, would you say that a "manual" install section would be enough, where I advise that the directory be created as part of the process? I'm already working on this.

That would probably work. The fact that your binary is completely self contained is a great plus imho. So you could also let the user specify the logFilePath with a command line argument and let them either put it in /root/ (default) or somewhere else. That way you can run the program without having to touch your filesystem.

(Maybe I'm very anal about this. I just don't like when I go through a box that's been up for years and find all kinds of stuff I can't remember putting there.)

**Comment by CryoByte33** [comment]
> So you could also let the user specify the logFilePath with a command line argument and let them either put it in /root/ (default) or somewhere else. That way you can run the program without having to touch your filesystem.

This is a good idea. I'll make an enhancement to allow for a flag that specifies log location!, thank you!

**Comment by CryoByte33** [comment]
Closing with the documentation improvements in #118 and the enhancement issue, #119, having been created.

Thank you again for the great feedback!
