### ISSUE TITLE
Missing Icon

### ISSUE THREAD

**Issue by solarisfire** [CryoByte33/steam-deck-utilities#121]
Brand new steam deck recieved today.

The first thing I do is install these utilities as per the video on youtube.

But I'm missing the icon file.
![PXL_20230322_161935571](https://user-images.githubusercontent.com/420952/226970385-8df2c141-a834-455b-a90d-042fb3a90498.jpg)

**Comment by solarisfire** [comment]
Ignore me...
Switching to gaming mode and back again fixed things.

**Comment by CryoByte33** [comment]
Ah yeah, this is a KDE issue, not CU. Thank you for being on top of the reports, though!
