### ISSUE TITLE
Compatdata information

### ISSUE THREAD

**Issue by Kazlehoff** [CryoByte33/steam-deck-utilities#126]
Hi Cryobyte. Im looking for a bit of additional information.

I have made a couple of scripts to help people modding Skyrim on the Steam Deck copy files from their windows PC  to a USB device, then from the USB device to their steam deck. its a batch file, and a shell script.

None of it is super advanced (if you'd like to take a look, i'll link my archive on mega) but i have a question.

Part of Skyrim involves the Compatdata folder. Its Ini's, two text files relating to mods (plugins.txt and loadorder.txt), plus its save files and logs.

my shell script for copying to the deck takes into account the location for the compatdata folder should always be /home/deck/.local/share/Steam/steamapps/compatdata/48930/.

What im trying to figure out [I cant just your app, because your app doesnt like games installed on SD for my particular system for absolutely no known reason](https://github.com/CryoByte33/steam-deck-utilities/issues/47),  is how that compatdata folder move is accomplished. is it Symlinks? 

what happens when a user who has copied their 48930 compatdata folder to a different location with your app then tries to copy to the default compatdata/48930 location on the internal storage?

**Comment by CryoByte33** [comment]
It's just a symlink 🙂

The compatdata and shadercache get moved, verified and then symlinked. As long as your script uses standard Linux tooling it _should_ be able to transparently copy into the symlink, but if not then you may need to find the symlink's pointer (if present) then use that to determine where to copy.

**Comment by CryoByte33** [comment]
Yeah that should work just fine through the symlink 🤔

**Comment by Kazlehoff** [comment]
awesome. thanks, appreciate the info. :D
