### ISSUE TITLE
[UI Bug] Window size too big on external display

### ISSUE THREAD

**Issue by Cederick** [CryoByte33/steam-deck-utilities#127]
So opening up CryoUtilities on an external display that is set to primary results in the windows to be many times too big. Opening it while it's undocked works fine.

External display is set to 1080p.

**Comment by weclock-droid** [comment]
I also have this issue

**Comment by RueGorE** [comment]
Can confirm, this happens to me too using the official Steam Deck Dock with a 1080p TV over HDMI. CryoUtilities UI is just gigantic and I have to move the window around to reach everything. So weird.

**Comment by Liam-DWS** [comment]
had the opposite happen while on the deck screen, UI was so small I couldn't see anything
