### ISSUE TITLE
Automatic TRIM disabled for version lower than 3.4 (3.3.2)

### ISSUE THREAD

**Issue by anghelos** [CryoByte33/steam-deck-utilities#13]
The script says that it detected an OS version that supports TRIM, even though I'm still running 3.3.2 (which does not, if I'm not mistaken)

**Comment by CryoByte33** [comment]
This is why you don't code before coffee, kids. Logic error, confirmed on my end and should be working with[ this commit](https://github.com/CryoByte33/steam-deck-utilities/commit/9728d207a8ab8a7e05146792129dccc771e528fb). Sorry 😓
