### ISSUE TITLE
Will it be compatible with DeckBTRFS

### ISSUE THREAD

**Issue by Mart-Bogdan** [CryoByte33/steam-deck-utilities#142]
I want to install https://gitlab.com/popsulfr/steamos-btrfs  but I am worried would it play well with [steam-deck-utilities](https://github.com/CryoByte33/steam-deck-utilities)?

**Comment by CryoByte33** [comment]
CU is compatible with steamos-btrfs since February in #23 , please let me know if you have any issues!

**Comment by Mart-Bogdan** [comment]
What bugs me is the swap file. As I understand this utitliity would enable it every time it is launched?

I would like to get rid of swap file completely, as I already have created SWAP partition of 20 GiB and SteamOS is automatically mounts it, so I don't need swap file anymore.

**Comment by CryoByte33** [comment]
Ah, I understand. CU will only create it if using the "easy" buttons on the main page, or the swap file resize directly. If you want to avoid this, just set each option manually, aside from swap file size.

As for "every time it's launched", I want to clarify that CU doesn't do anything when opened. It _will_ create a systemd service that will reset your settings on boot, but that's it 🙂

**Comment by Mart-Bogdan** [comment]
Thank you very much. 

Such quick reply.

> It will create a systemd service that will reset your settings on boot, but that's it slightly_smiling_face

So you mean that system service would re-apply other settings, but swap is one time operation?

**Comment by CryoByte33** [comment]
> So you mean that system service would re-apply other settings, but swap is one time operation?

Correct, swap resize is a one-time operation, the others need to be reset each boot.
