### ISSUE TITLE
Battlefield 1 Videos became laggy after CryoUtilities

### ISSUE THREAD

**Issue by z11on** [CryoByte33/steam-deck-utilities#144]
Hey there, thank you very much for the tool, I love it! However, I ran into the subj issue. All the options in CryoUtilities are green, and I do not even know where to start tweaking =\ please help!

**Comment by CryoByte33** [comment]
Hey there, thanks for using CU and I'm sorry that you're having problems!

This is the first I've heard of this, especially sobering as simple as videos playing. Can you try rebooting the Deck and seeing if the issue persists?

**Comment by z11on** [comment]
Unfortunately, rebooting did not help(that would be too easy though). Here is what it looks like: https://www.dropbox.com/scl/fi/r42jrjju4hcxgvl5jjd37/Battlefield_1.mov?rlkey=tostcohpfazb4v8d4hn1grb7r&dl=0

The game is located on the SanDisk Ultra 1TB, and before the CU it had no issues with video playback. What would you suggest to try first?

**Comment by CryoByte33** [comment]
That's... interesting, nothing CU does should cause anything like that, all I do is prevent extraneous memory operations from causing stutter.

If I had to take a wild stab in the dark, try disabling HugePages, reboot and test again 🤔

**Comment by z11on** [comment]
I'm so sorry! CryoUtilities is absolutely not to blame for this glitch! It turns out that I screwed up the frames per second limit almost immediately after I installed CU, and didn't take it into account. And that was the cause of the problems.

So it's completely my fault. Again, I apologize for the inconvenience. 😐
