### ISSUE TITLE
Mouse sensitivity problem

### ISSUE THREAD

**Issue by HankeMat** [CryoByte33/steam-deck-utilities#146]
After installing and running this program the sensitivity of the right joystick increses after a while of playing. Happened to me and to my friend as well.

**Comment by CryoByte33** [comment]
Can you try rebooting? It might be that the UI is increasing scaling temporarily, but the program itself does nothing that could do this in any way.

**Comment by HankeMat** [comment]
Yeah, I did rebooted and now it works just fine. I'll let you know if it goes wierd again. Just wanted to mention it because it happened a while after installing to me and even my friend. Sorry if that was a false alarm.
