### ISSUE TITLE
Steam deck lost display after installing and running cryotools!

### ISSUE THREAD

**Issue by ggrell** [CryoByte33/steam-deck-utilities#147]
I have a Steam Deck, and installed cryotools to the desktop, ran it and chose the defaults (top button first screen). After that completed, I looked through the changes it made, only the last screen showed I had 1GB VRAM set, so I shut down the device from desktop to boot to BIOS. Now when I power it on, I hear the fan spin up but there's no more video output on screen (or HDMI adapter). I also tried Vol UP + Power, Vol DN + Power, nothing. 

Any idea what it might be, or how I can get it back up & running? Thanks!

**Comment by ggrell** [comment]
Looks like after about 8 attemps, it came back.

**Comment by CryoByte33** [comment]
It was likely training memory, it can take a few minutes after messing around in BIOS. The good news is that CU didn't cause it 🙂

Thanks for using it!
