### ISSUE TITLE
Guidance for CryoUtilities on Bazzite

### ISSUE THREAD

**Issue by knaackville** [CryoByte33/steam-deck-utilities#151]
This may be a niche case, but I recently migrated to Bazzite on my Steam Deck.  Any suggestions for which parts of CryoUtilities would be beneficial (or which ones should not be enabled)?  

I assume the swap file and swappiness aren't a good idea to enable with ZRAM (though ZRAM could be disabled if the swap settings are still significantly beneficial).  Any thoughts on the memory parameter tunings?

Thank you!

**Comment by CryoByte33** [comment]
All of the "tweaks" that don't deal with the swap file will be equally beneficial as on SteamOS 🙂

**Comment by knaackville** [comment]
Awesome!  Thank you for the quick response.
