### ISSUE TITLE
Game data does not sync to other partitions on the same drive

### ISSUE THREAD

**Issue by sjaksshsi** [CryoByte33/steam-deck-utilities#152]
I am using Steam OS-Windows hybrid.
In the same physical SSD, for example, Steam OS is installed on the C drive and Windows is installed on the D drive.

Game data seems to sync well between the C drive (Steam OS), and Micro SD.
But if try to sync game data between the C drive and D drive, symlink error appear and sync not proceed.

Is syncing not working in different partitions between the same SSD?

**Comment by CryoByte33** [comment]
It definitely does since it just uses the mount path, but you need to use the "SteamOS default" mount paths.

**Comment by sjaksshsi** [comment]
It's a little disappoint because Steam os drive is almost full but as you said, it seems not a problem.
Thank you for answer :)

**Comment by CryoByte33** [comment]
Just to be clear, you CAN sync it to another partition on the same drive, it just needs to be mounted in the proper location on SteamOS, which you can specify 🙂
