### ISSUE TITLE
Installation Process Deadend right at the start

### ISSUE THREAD

**Issue by BlackRedDead** [CryoByte33/steam-deck-utilities#156]
Hey, i would really like to use your tool, sadly the described installation parts make no sense:
1. downloading the latest "[cryo_utilities](https://github.com/CryoByte33/steam-deck-utilities/releases/download/latest/cryo_utilities)" and trying to execute it does nothing, at least nothing happens visibly for ~10-20min while i was searching a solution (tho not really a surprise, as the file lacks an extention to tell the system what to do with it - so if it has to be renamed, where to find that crucial information what to add?)
2. following the instructions at [Install simple](https://github.com/CryoByte33/steam-deck-utilities#simple) leads nowhere, as the "link to save" is a .txt file - how to execute that? - as certainly "double-tap/click" only opens it in a text editor!

Tbh - i'm rather new to steam deck and still a beginner with Linux, despite using it since 2 years - so i might still miss some crucial information, but "given as is", the description leads nowhere and is/should be meant for average users (well, with basic knowledge about hardware) - so in my conclusion this is not (entirely) a "me" problem, but rather misleading or outright wrong description.

**Comment by CryoByte33** [comment]
Heya, thanks for using CU!
Try following the "simple" instructions, then rename the file from ".txt" to ".desktop". Make sure the file is on the desktop and then double click it and see if that works!

> but "given as is", the description leads nowhere and is/should be meant for average users (well, with basic knowledge about hardware) - so in my conclusion this is not (entirely) a "me" problem, but rather misleading or outright wrong description.

To be clear, the video in the description is meant to be mandatory viewing, as I show how it should be installed. I also followed the "simple" instructions last week and didn't have any issues so it's a bit unclear why yours isn't working 😅

**Comment by BlackRedDead** [comment]
yea, just realized after watching a(nother) video where the issue was - had it doublechecked with my notebook but that also seems to have turned the .desktop into a .txt, tho now it doesn't... - so had you fixed it?

And what video? - the "[announcement Video](https://youtu.be/C9EjXYZUqUs)" under [Explaination & Tutorial](https://github.com/CryoByte33/steam-deck-utilities#explanation-and-tutorial)? - i had watched it before i even ordered my Steam Deck, so beside installation i still know what to expect :-)

Still thank you for the fast reply, have a nice time of day (^.^)-d

**Comment by CryoByte33** [comment]
I haven't changed anything in a few months so I'm not sure what changed, but I'm glad you fixed it! Sorry for the issue, I'm really not sure where it went wrong!

**Comment by BlackRedDead** [comment]
well, seems to be an issue with the steam deck recovery holo os maybe?
also, i don't have an icon for the application (like it's shown in the video :-/
my steamdeck got upgraded with an 1TB SSD and thus reimaged, but i haven't heavily changed the system (only within system settings), especially not icons, tho it should be custom downloaded so not sure what the hell went wrong...

**Comment by BlackRedDead** [comment]
Also some suggestions:
- having recomendated values also marked (like defaults are)
- being able to set values for "Page Lock Unfairness", as there can be issues with such an extreme value as "1" instead of "5" (i would personally like to set it to 3, so a process that might need quick successen access can still have that with less interuption of other processes)
- recommended vram should be 2G(B), as factorio as example can easily chew trough RAM, while barrely needing more than 2GB VRAM! (and as the steamdeck will allocate both dynamicly depending on the need, and propably prioritizes VRAM anyway, increasing minimum VRAM to 4G(B) will just limit RAM to 12GB, wich some games laugh sinister about and love eating well above 16-32GB of RAM (Space Engineers as another example - tho, that game is just wasteful with what it loves to leave in RAM xP - but it also just needs lots of RAM with complex builds ¯\_(ツ)_/¯ )

**Comment by CryoByte33** [comment]
- Recommended, this is a good call, I'll try to implement it!
- PLU, this is something I wanted initially, but it slipped through the cracks, another good suggestion!
- Recommended VRAM, this I disagree with. Some COU-heavy games like Factorio or Civ work better with less, but almost every game that has a major FPS bottleneck benefits from the additional VRAM, at least on my testing of SteamOS 3.4.x and below 🙂

Thank you for the suggestions!

**Comment by BlackRedDead** [comment]
well, it seems maybe just HoloOS is strange? - now the icon is there... (or maybe just needed a restart xP)

About the VRAM prioritization and reservation - i find conflicting informations about the way it actually works... :-/
Do you know for sure if eighter RAM or VRAM is prioritized in allocating Memory? (i mean the bios setting to increase reserved VRAM only makes sense to me if RAM has priority over VRAM usage...)

Regarding the games / factorio, not sure how it should perform better with less RAM? (technicly, i admit my background is more in hardware than software and i'm rather an very experienced user with good technical understanding, but not even close to a programmer, just a modder ;-) - so i might get things wrong,but always open for facts to change my mind :-)

...well, i go and get you some data to look at^^
