### ISSUE TITLE
Suggestion - Use Application Launcher instead of Desktop Shortcuts

### ISSUE THREAD

**Issue by JohnnyBlocks** [CryoByte33/steam-deck-utilities#16]
### Suggestion - Use Application Launcher instead of Desktop Shortcuts

It would be really neat if the install script would give the option to create Application Launcher shortcuts.

It could be an option to where the user wants them... desktop or application launcher.

I envision your logo as a Application Section with the three icons in it.   (utilities, uninstall, update)

Appreciate you and your work.. just wanted to offer a quality of life suggestion.

**Comment by CryoByte33** [comment]
Heya, thank you for the suggestion! I have a new update in development which does exactly this 🙂

I'll leave this issue open until the update is actually live, and hopefully it won't take to long!

**Comment by CryoByte33** [comment]
The update has been released, details at https://youtu.be/C9EjXYZUqUs, closing this issue!
