### ISSUE TITLE
[Question] in 3.4 what runs the Trim ?

### ISSUE THREAD

**Issue by LucidityCrash** [CryoByte33/steam-deck-utilities#17]
Sorry this isn't really your issue but I'm trying to work out how the trim is scheduled in SteamOS 3.4, I asked in a Reddit group but only got one answer that I don't believe is correct ... it's not the systemd timer, its not cron and its not a mount option either in the fstab or a default option in the filesystem options (tune2fs).

I found a script /usr/lib/hwsupport/trim-devices.sh which is called buy another script /usr/bin/steamos-polkit-helpers/steamos-trim-devices which has a polkit action defined.  I'm assuming these are the bits doing the actual trim but do you happen to know what is actually doing the scheduling ?

**Comment by CryoByte33** [comment]
Lol don't make a habit of it, but it's fine this time.

All of Valve's "scheduled" polkit tasks, including TRIM is called from `/usr/share/polkit-1/actions/org.valve.steamos.policy`. 
It's an XML file that specifies it all, but is frequently overwritten so make sure not to modify it too much.

**Comment by LucidityCrash** [comment]
Thanks ... I'd found the polkit files.  The bit that confuses me is I thought polkit was about authorising non privileged apps interacting with things that require privileges, though I'm behind the curve on Polkit ... so in this case it allows something running as a non root user to execute a script ( /usr/bin/steamos-polkit-helpers/steamos-trim-devices) which executes another script (/usr/lib/hwsupport/trim-devices.sh) which executes fstrim in this particular case.  But what is the thing that actually has the schedule in it ?

**Comment by CryoByte33** [comment]
Ohh yeah, I think that's the actual Steam client itself, I haven't found any "normal Linux scheduling" either, sorry I misunderstood.

**Comment by LucidityCrash** [comment]
Thanks.

**Comment by Bitwolfies** [comment]
Good to see this question asked as I was very curious as well. If I had to guess it and the rest of the 20 or so polkits valve has created are all executed by the custom steam-Jupiter client, since there’s one for fan control as well. Very odd regardless to not rely on systemd’s timer however.

**Comment by LucidityCrash** [comment]
I'm guessing the manual run from game mode will be tied into it ... using
their own scheduler with polkit makes for a simpler solution.
