### ISSUE TITLE
Wrong stock settings

### ISSUE THREAD

**Issue by bargu2** [CryoByte33/steam-deck-utilities#172]
Since the release of SteamOS 3.5, the default settings for swappiness has changed to 60 from 100 and huge pages is on by default. Clicking on Stock Settings on the CryoUtilities it's setting incorrect values.

**Comment by CryoByte33** [comment]
Good catch, this is definitely a bug! IN the meantime, if you reboot after reverting to stock it should be 60, but I'll try to fix this soon!

**Comment by bargu2** [comment]
The Huge Pages toggle should probably be removed from the app since there's
no real reason to turn it off anymore.

**Comment by CryoByte33** [comment]
Some games, particularly Halo, crashes with Huge Pages on so I'll be leaving it for the time being 🙂

**Comment by zr00da** [comment]
Applying Recommended settings now results in "Shared Memory in THP", "Compaction Proactiveness", "Defrag" and "Page Lock Unfairness" showing red in the Memory tab.

**Comment by gensosuikoden** [comment]
> Some games, particularly Halo, crashes with Huge Pages on so I'll be leaving it for the time being 🙂

Would there be any disadvantage for me just to leave Huge Pages set to ‘OFF’ in Cryoutilities, and just toggle  it on/off as needed in real-time in-game using the Decky Loader plug-in “System Tool Box”?

Many thanks in advance

**Comment by dreampiggy** [comment]
Thanks to point this out since SteamOS 3.5

**Comment by CryoByte33** [comment]
> > Some games, particularly Halo, crashes with Huge Pages on so I'll be leaving it for the time being 🙂
> 
> Would there be any disadvantage for me just to leave Huge Pages set to ‘OFF’ in Cryoutilities, and just toggle it on/off as needed in real-time in-game using the Decky Loader plug-in “System Tool Box”?
> 
> Many thanks in advance

Nope, you can definitely do that and it should function identically, since both CU2 and System Toolbox do the same thing behind the scenes.

**Comment by CryoByte33** [comment]
> Applying Recommended settings now results in "Shared Memory in THP", "Compaction Proactiveness", "Defrag" and "Page Lock Unfairness" showing red in the Memory tab.

I wasn't able to replicate, could you try again and open another issue if the issue persists?
