### ISSUE TITLE
Does not install on fresh 3.4

### ISSUE THREAD

**Issue by ggppjj** [CryoByte33/steam-deck-utilities#18]
Hello! I'm setting up some new Decks and the utilities never actually install using the desktop shortcut that gets downloaded. It runs and silently errors somewhere along the way and I have no idea why it isn't working.

Happy to help debug, but this issue seems to be a universal one as multiple decks are unable to install it following the instructions on the repo. I've set a root password and it never actually asks me to put it in. I'm assuming the lack of root password is my issue, but running the command from the desktop file as sudo does nothing either. I have to manually run the install line by line myself, no issues running through it manually.

**Comment by ggppjj** [comment]
I saw your response to a similar report [here](https://www.reddit.com/r/SteamDeck/comments/zsg8dh/to_anyone_whos_used_cryoutilities_or_updated/j19v89q/), I also set as executable. I'll try again now and report back.

**Comment by ggppjj** [comment]
This was my issue. Leaving open and will submit a pull request with updated verbiage on the readme if that's ok.

**Comment by CryoByte33** [comment]
PR merged, thank you again!
