### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by Aepoh** [CryoByte33/steam-deck-utilities#188]
No new releases in almost a year and also a lack of responses to technical questions in the issues in regards to whether the application still even does what it says it does.

**Comment by CryoByte33** [comment]
I've provided some updates as to the status of this project in the discord, as well as how it functions in 3.6. 

TL;DR: It's not dead, but real life has gotten in the way. A new update is most of the way completed, and will be released alongside a video when it's done.

**Comment by rujash7** [comment]
@CryoByte33 Thank you, I will hold off until then... I really want to have a solid solution for even across steamos updates, integrated nicely with ui, to set swappiness and swap file. Those alone would give 80% of what is attractive for it

**Comment by Aepoh** [comment]
Steam OS 3.6 has come and gone so I imagine that pushes any future release of this project further behind.
