### ISSUE TITLE
Swap Resizing and the 64GB Steam Deck

### ISSUE THREAD

**Issue by syberphunk** [CryoByte33/steam-deck-utilities#20]
Does the Swap Resizer check to see if it can/should resize the SWAP before enacting it?

Such as if there's enough space available to resize the swap?

If it doesn't, could it do some safety checks to ensure that it should/can before it does anything?

Because a user with a 64gb steam deck ran the utilities, and resulted in a steam deck that wouldn't boot, it was exhibiting the "flashing" problem where it attempts to start up, shows the cursor in portrait mode, and then doesn't boot further.

Attempting to recover from this by 'booting previous' with (. . .) and Power, managed to get the user into gamescope, and erase some games from the SSD, but couldn't boot into Desktop mode. Rebooting the steam deck resulted in the same flashing behaviour and was unable to then 'boot previous' again.

The user had to then factory reset / re-image the steam deck.

**Comment by CryoByte33** [comment]
Hey, thanks for opening an issue!

This feature [has already been implemented](https://github.com/CryoByte33/steam-deck-utilities/blob/main/cryo_utilities.sh#L44) but I'm curious how you were able to enter a boot loop after it started.
In particular, the script checks the available space at the beginning of the resize, but if something else is writing to the drive at the same time, the script doesn't know that it's happening. 

Do you think that Steam might have been downloading something in the background and maybe filled your drive while the resize was happening?

**Comment by syberphunk** [comment]
The person whom was experiencing this issue, and I had to help them out of it, was not downloading something in the background at the same time.

They simply were able to run the install, ran the GUI, and setup the swap and similar in a fashion that resulted in 1.5MB of space left in their home partition.

They booted to a recovery environment and they were able to mount the home partition, deleted some 5GB of files and were able to boot.

They discovered that the script hadn't properly resized/created the swap file to the amount they had set (which was 8GB or 10GB) and they believe that's what had filled their drive storage.

**Comment by CryoByte33** [comment]
I don't suppose a screenshot of the debug information is available? I'm confused as to how it could have happened, unless the drive reported a different amount of space than what was actually available.

I do have an update in development that can have a dynamic "fudge factor", and will allow me to specify how close to full the drive can get, but if it's not being respected at all I'm not sure how if it would help.

**Comment by syberphunk** [comment]
Sorry I don't have that information available.

**Comment by CryoByte33** [comment]
Cleaning up issues right now. I guess I'll close this as I've verified the old code works, but background processes continue to write during the resizing process. As mentioned above, the new update of CU has a "buffer" of 1GB built in so it won't allow you to re-line the space on the drive.
