### ISSUE TITLE
[Idea] Hugepages Support

### ISSUE THREAD

**Issue by WingofaGriffin** [CryoByte33/steam-deck-utilities#22]
Seems like it's in the same vein. Adding a systemd service along the lines of https://www.reddit.com/r/SteamDeck/comments/10723yd/permanently_enable_transparent_huge_pages_at_boot/

Where we can create the file, then start and enable the service similar to decky.

```
[Unit]
Description=Enable Transparent Huge Pages (THP) 
[Service]
Type=simple 
ExecStart=/bin/sh -c "echo 'always' > /sys/kernel/mm/transparent_hugepage/enabled" 
[Install]
WantedBy=multi-user.target 
```

**Comment by kyle-mace** [comment]
Thanks for opening this issue! Huge Pages support is already planned for the next major version, and is already partially implemented on my end 😁

I'll leave the issue open until the new version is public, just to make sure everyone knows when it gets released, thank you again!

**Comment by CryoByte33** [comment]
Thank you for opening an issue! THP support is already planned and partially implemented on my end for the next major version of the script 🙂

I'll leave this issue open until the feature has been released, thank you again for helping out!

**Comment by FerLuisxd** [comment]
Any ETA's?

**Comment by CryoByte33** [comment]
@FerLuisxd I hope to have it out to patrons for testing in the next month or so, depending on how my day job is. If they report that it hasn't broken anything horrendously, then not too long after that 🙂

**Comment by CryoByte33** [comment]
The update has been released, details at https://youtu.be/C9EjXYZUqUs, closing this issue!
