### ISSUE TITLE
[Suggestion] BTRFS support (https://gitlab.com/popsulfr/steamos-btrfs)

### ISSUE THREAD

**Issue by marissa999** [CryoByte33/steam-deck-utilities#23]
I just used the steamos-btrfs payload to convert my home partition to btrfs. Now it seems like this also had an impact on my swapfile
```
(deck@marideck ~)$ swapon -os
NAME                     TYPE  SIZE  USED PRIO
/home/@swapfile/swapfile file 1024M 11.8M   -2
```
I tried to rerun the CryoUtilities-Script, but I stopped the program when it said that my swapfile is 0 bytes, which indicates that it can not even see the new swapfile. I did not proceed any further. 

The swapiness is still the configured 1, even after fully restarting the Deck, so that seems to still work.
```
(deck@marideck ~)$ cat /proc/sys/vm/swappiness
1
```

It seems like this was enough for me to temporarily* change the swapsize from 1GB to 16GB
```
sudo swapoff /home/@swapfile/swapfile
sudo dd if=/dev/zero of=/home/@swapfile/swapfile bs=1G count=16 status=progress
sudo mkswap -U clear /home/@swapfile/swapfile
sudo swapon /home/@swapfile/swapfile
```

This results in
```
swapon -os
NAME                     TYPE SIZE USED PRIO
/home/@swapfile/swapfile file  16G   0B   -2
```

*This also stays the same after a reboot, but I would not bet on this still staying the same after updates. 

Do you think it would be possible to configure your tool so that it can detect if it uses a btrfs subvolume for the swapfile, and if so resize it? Though if this is not getting implemented that would be totally understandable, keeping up with the changes from a different script, which heavily modified the deck itself does sound like a lot of work that could easily break.

**Comment by CryoByte33** [comment]
Hey, thanks for opening this issue!

So, this script did actually work with BTRFS prior to a recent update on his end. In the past, they created a hardlink to /home/swapfile which I was still able to resize "through", but now they remove it outright and broke this script.

No guarantees, and I don't have a Steam Deck that I can install BTRFS on at this time, but I should be able to use a VM to test and implement experimental support in the next release, which is about a month out.

**Comment by marissa999** [comment]
Apparently it should still work, and I need to rerun the script. So totally my fault for making this issue, I just did not want to potentially break something by rerunning the tools after it detects no swapfile at all :D
https://gitlab.com/popsulfr/steamos-btrfs/-/issues/55#note_1265755301

**Comment by CryoByte33** [comment]
Sorry for the delay, did re-running the script work? I'm happy to add manual support for the new file location if necessary, but I don't have a device to test with 😅

**Comment by CryoByte33** [comment]
The update has been released, details at https://youtu.be/C9EjXYZUqUs, closing this issue!
