### ISSUE TITLE
503 Egress is over the account limit.

### ISSUE THREAD

**Issue by rahatzamancse** [CryoByte33/steam-deck-utilities#26]
Hi, while installing the script by double clicking, nothing happens. Then I tried to run the install script from shell, and found the following error while the script tries to clone the repo.

`503 Egres is over the account limit.`

**Comment by CryoByte33** [comment]
Interesting, I just tried and it worked fine. A quick Google says that GitHub themselves might be over some sort of limit?

...did I break GitHub?

**Comment by rahatzamancse** [comment]
Yeah, I just tried it now and it also worked for me. Maybe a Github issue. Closing now.
