### ISSUE TITLE
Disclaimer for prefix/cache deletion

### ISSUE THREAD

**Issue by bugworm** [CryoByte33/steam-deck-utilities#30]
Since deleting prefix may cause some irreversible changes (missing saves, mostly), this menu should have some sort of disclaimer. I know you addressed this in your video, but it will be nice to add it directly to a program itself so people won't complain for no reason.

**Comment by CryoByte33** [comment]
Great idea! I marked this as an enhancement and will try to implement it in the coming days.
Thank you!

**Comment by CryoByte33** [comment]
This was resolved with updated verbiage in #91
