### ISSUE TITLE
GUI is unusable supersized

### ISSUE THREAD

**Issue by MrSco** [CryoByte33/steam-deck-utilities#32]
![BBFD26C3-8759-4CFF-B1E6-0D4A2BE4684A](https://user-images.githubusercontent.com/11297411/220112154-83c84ebb-b9f5-48c8-bc77-ab2534957684.jpeg)

**Comment by ajite** [comment]
Hi,

Can you try to update to the latest version and try again?

If it does not work after the updat:

Can you send the output of:

`cat /home/deck/.cryo_utilities/launcher.sh`

And can you try to run directly from the terminal see if that fixes it:

`FYNE_SCALE=1 /home/deck/.cryo_utilities/launcher.sh`

**Comment by MrSco** [comment]
> Hi,
> 
> Can you try to update to the latest version and try again?
> 
> If it does not work after the updat:
> 
> Can you send the output of:
> 
> `cat /home/deck/.cryo_utilities/launcher.sh`
> 
> And can you try to run directly from the terminal see if that fixes it:
> 
> `FYNE_SCALE=1 /home/deck/.cryo_utilities/launcher.sh`

Already was running latest version.

```
1)(deck@steamdeck ~)$ cat /home/deck/.cryo_utilities/launcher.sh
cat: /home/deck/.cryo_utilities/launcher.sh: No such file or directory
```

**Comment by ajite** [comment]
That's weird. You don't have a launcher.sh under ~/.cryo_utilities.  Can you right click on "CryoUtilities" on your desktop then click on "Properties" -> "Application" and take a screenshot ?

The app was updated a few hours after he published the video. That's why I thought it might not be up to date.

**Comment by MrSco** [comment]
![image](https://user-images.githubusercontent.com/11297411/220128707-0cd771d3-fa93-4662-9684-17eb87cf202e.jpg)

**Comment by CryoByte33** [comment]
launcher.sh missing is fishy, could you try updating and see if it appears? It sounds like you just downloaded the release artifact and are running that.

**Comment by CryoByte33** [comment]
@MrSco Ohh yeah, you need to run with the one with an icon, not that file. Make sure to use the "Update CryoUtilites" icon, then the "CryoUtilities" icon with the picture, not the one you just clicked on.

**Comment by MrSco** [comment]
Yep. That was it. Working now. Thanks.
