### ISSUE TITLE
Recommended Setting Causes Hogwarts Legacy to Crash

### ISSUE THREAD

**Issue by Eastiling** [CryoByte33/steam-deck-utilities#35]
Hi,

After enabling the recommended setting in the tool Hogwarts Legacy will crash shortly after loading into a game and moving around a little, firing some spells etc. I've see it happen fairly consistently around 10 - 15 seconds after save loading.

I have the 256GB Steam Deck with 4GB VRAM setting applied. Hogwarts is installed on the SSD and the drive has plenty of space (80GB) free. No other games are running at the same time and running the game in Game Mode.

I returned to the tool, hit 'Stock Settings' and reloaded the game. The issue was gone, no crashing again. Reapplying the recommended setting caused the crash to occur once more. Reverted to stock, fixed.

After this I've done a little testing but not much:

- Re-enabling the 16GB swap file and swapiness of 1 resulted in NO crash, I can confirm the game runs better than stock as well. Interestingly some graphical issues I'd noticed have been fixed as well. (I did have the VRAM set at 4GB before as I hadn't realised changing that without an increased SWAP file might be a bad thing. Could that be why?).

- Enabling the settings on the Memory tab causes no crashing, all toggled on.

- Perhaps something to do with the storage tab? For now enabling all setting except those in the storage tab seem to work for me for this game. As I have a mid range SSD in my Deck I'll leave those alone. Not sure if those are the cause in some way or if the recommended settings changes something else that might be causing it.

Regardless of the slight issue for this one game, thanks for the excellent tool and video. I can definitely say its helped a good bit once I did the steps above manually. I can't say if this is just a 'my deck' issue, but hopefully helps others if they have the same problem.

**Comment by CryoByte33** [comment]
This is very interesting, as I've had numerous reports of Hogwarts Legacy working much _better_ with the new version. Would it be possible to test with each setting in the "memory" tab one-by-one to narrow it down?

**Comment by Eastiling** [comment]
That's how I did things. First enabled the swap settings, went back to the game in Game Mode. All fine.

Then did the same for each setting in the Memory tab. Enable one, go back to Game Mode and start the game. Test. Then enable the next setting. By the end of all the settings I still had no crash.

I can confirm the games a good deal better than stock with these applied. I can't say why hitting recommended breaks it for me. I just left the storage settings alone.

**Comment by CryoByte33** [comment]
Veeerrrrry weird. Any chance you'd be willing to press "recommended" and then reboot to see if the issue persists?

**Comment by Eastiling** [comment]
Very weird indeed.

Went back and reset to stock, then hit the recommended setting. Reloaded the game and... its fine?

It was pretty consistent earlier, I wouldn't have raised an Issue otherwise... 

So its either something about going through the testing that let my game/save skip the crash issue or I guess more likely a 'my deck' issue. I'll keep an eye on the game and see if the crash happens again at some point. 

I can confirm I didn't have any issue before hand and had but about 19h into the game on the Deck beforehand.

**Comment by CryoByte33** [comment]
No idea why a reboot would help, either. Maybe there was something stale in memory and the reboot cleared it up? I'm happy that it's fixed, but now I'm more confused!

I guess I'll close this for now, feel free to reopen if it starts happening again🙂
