### ISSUE TITLE
Certain characters in sudo password may cause authentication failure

### ISSUE THREAD

**Issue by CryoByte33** [CryoByte33/steam-deck-utilities#36]
A user reported a password with `(` in it as not working correctly. Investigate the auth function.

**Comment by CryoByte33** [comment]
I'll test fixes for this after #31 gets merged, best to wait until we're Go developer approved before changing anything major.

**Comment by ajite** [comment]
Seems #31 fixed it. I tried a few passwords with `( ` and other special characters.

**Comment by CryoByte33** [comment]
Perfect, closing.

**Comment by L11R** [comment]
@CryoByte33 still not able to enter `()` symbols with virtual keyboard.
