### ISSUE TITLE
.desktop download recommendation

### ISSUE THREAD

**Issue by MissLav** [CryoByte33/steam-deck-utilities#38]
id recommend putting a the .desktop in a zip to avoid the auto download issue or including a 2nd link for people having the download issue since for me the problem continued after rebooting 

so i had to just copy paste it into a text file and rename that txt to .desktop

**Comment by CryoByte33** [comment]
I was actually planning on swapping the curl for a wget, do you think that would be acceptable? Zipping it is annoying since it basically becomes a blob 😅

**Comment by MissLav** [comment]
not sure on the differences between curl and wget so idk

and gottcha 

maybe put the .desktop in releases? not sure if it would run into the same download issue

**Comment by CryoByte33** [comment]
It would, unfortunately. I had a similar issue with the binary when I rolled the update out this morning, and fixed it by using wget. I'll see about changing it locally tomorrow and hopefully it works well.

Thank you for reporting the issue!

**Comment by MissLav** [comment]
> It would, unfortunately. I had a similar issue with the binary when I rolled the update out this morning, and fixed it by using wget. I'll see about changing it locally tomorrow and hopefully it works well.
> 
> Thank you for reporting the issue!

nw! thank you for making this tool wouldn't had known about it if i didn't see u and gamingonlinux talking about it on the fediverse

**Comment by CryoByte33** [comment]
I think I may have initially misunderstood your issue. I read this as the installer failed, but you're saying that right click download didn't work for you?

**Comment by MissLav** [comment]
correct

**Comment by CryoByte33** [comment]
Ahhh okay, this is a known bug with KDE/Firefox and there's a step in [the troubleshooting section](https://github.com/CryoByte33/steam-deck-utilities#troubleshooting) about it. 

Sorry for the misunderstanding, I was at work and should have spent more time parsing this 😅

Since this isn't specific to this repo, and I've replicated on other sites, I'll close this and try to think of a better way to distribute in the future.
