### ISSUE TITLE
Bug in swappiness conf file?

### ISSUE THREAD

**Issue by MCPtz** [CryoByte33/steam-deck-utilities#4]
This logic looks suspicious:
```
sudo sysctl -w "vm.swappiness=$SWAPPINESS_ANSWER"
if [ "$SWAPPINESS_ANSWER" -eq "100" ]; then
    sudo rm /etc/sysctl.d/zzz-custom-swappiness.conf
else
    echo "vm.swappiness=$SWAPPINESS_ANSWER" | sudo tee /etc/sysctl.d/zzz-custom-swappiness.conf
fi
```

Should it be more like, just overwrite the contents of`/etc/sysctl.d/zzz-custom-swappiness.conf` with the user selected swapiness?

```
sudo sysctl -w "vm.swappiness=$SWAPPINESS_ANSWER"
echo "vm.swappiness=$SWAPPINESS_ANSWER" | sudo tee /etc/sysctl.d/zzz-custom-swappiness.conf
```

Do we even need the conf file to preserve the vm.swappiness on reboot?

**Comment by CryoByte33** [comment]
I leave that there so people can permanently revert to default, or revert if Valve should apply a fix of their own. I originally had it the way you describe, but then users would have to remove the file manually if that situation ever arose.

**Comment by MCPtz** [comment]
Yea I was just confused by the logic. But if we go over it again, it's like you said.

Closed: Won't do :)
