### ISSUE TITLE
Can't check the CryoUtilities version through the GUI.

### ISSUE THREAD

**Issue by gezawatt** [CryoByte33/steam-deck-utilities#40]
This is more of a suggestion than an issue, but I think it would be useful if you could check the version of the app trough the GUI. So that you could verify that you're running the latest version with all the latest patches.

**Comment by ajite** [comment]
I agree. It would be useful.

@CryoByte33 how do you handle versioning ?

If you don't already have a process, can we use something like semantic release (https://github.com/go-semantic-release/semantic-release) ?

**Comment by CryoByte33** [comment]
Currently the version is just set in internal/config.go, and already follows SemVer (2.0.0), but I need to actually add the versioning to CI/CD in the release flow. The version is already printed to the log on the Deck, but it would definitely be a good idea to add it to the UI.

I won't have time to work on this in the next few days, but I'll definitely try to get to it soon!

**Comment by CryoByte33** [comment]
This is completed, closing.
