### ISSUE TITLE
Add required libraries/tools to install section

### ISSUE THREAD

**Issue by epechuzal** [CryoByte33/steam-deck-utilities#42]
Just followed the install instructions and now get this when I try to run the utility:
```
(deck@steamdeck ~)$ sudo ~/.cryo_utilities/cryo_utilities help
[sudo] password for deck:
/home/deck/.cryo_utilities/cryo_utilities: /usr/lib/libc.so.6: version `GLIBC_2.34' not found (required by /home/deck/.cryo_utilities/cryo_utilities)
```
I am assuming I am missing some shared libs or there is some other tool I need to install but I can't see what it might be based on the install instructions from this repo

**Comment by CryoByte33** [comment]
It sounds like you probably broke out of read only and used pacman? This just means that libc is broken, which shouldn't be the case on a stock Deck 🤔

**Comment by epechuzal** [comment]
I saw you replied to me on reddit, thank you - if this is supposed to work on a stock deck then I'm gonna close this out, clearly I've done something wrong :)

**Comment by RenanGreca** [comment]
I'm also having this issue. @epechuzal , if you found a solution to it, would you mind sharing the link here for future reference?

**Comment by epechuzal** [comment]
@RenanGreca you beat me to it, I was going to tell you to update to v3.4.4 which is the current version.

Previously I had v3.3.3 when I was hitting this bug

**Comment by CryoByte33** [comment]
Good catch, thank you! I think I'll try downgrading the version of Ubuntu used by the builder, that MAY resolve this.
