### ISSUE TITLE
Enhancement: List the changes which will be made when selecting "Recommended settings"

### ISSUE THREAD

**Issue by ekirchman** [CryoByte33/steam-deck-utilities#48]
It would be more transparent to the user to give a heads up about what changes are about to be made before the script performs the changes. This could be done in the prompt that shows up after clicking the "Recommended" button. Otherwise, the user may find it difficult to understand what was changed from the default.

IE have a short list which states in the prompt:

- Swap file set to 16GB with a swappiness of 1
- Enable Huge Pages
- Enable shared memory in THP
...

etc, etc...

**Comment by CryoByte33** [comment]
The idea was that the video was the manual, but this is a good idea. Thank you for the idea!

**Comment by Kazlehoff** [comment]
> The idea was that the video was the manual, but this is a good idea. Thank you for the idea!

A point, not everyone wants to watch a video for a manual. im one of them. a written guide to what the settings do would be beneficial.

I know what the swap file is, and why making it bigger is good, and why having the OS use the swap file before the ram is dumb, but for example: what is huge pages, and why change it? What is Shared Memory in THP? What is Compaction proactive-ness? Page lock unfairness?

**Comment by CryoByte33** [comment]
> A point, not everyone wants to watch a video for a manual. im one of them. a written guide to what the settings do would be beneficial.

I plan on making a guide for these in the docs folder in a few days.

_That said_, the primary goal of my channel is education, and this entire project was actually just a spin-off of that. All of those things and more are explained in the video, in a way that I feel is much better shown than written.

Obviously, not everyone agrees and I'll be making the guide for a reason, but I still think that claiming that information doesn't exist when there's a video dedicated to those topics is a little silly 😅

**Comment by Kazlehoff** [comment]
Im glad to hear you're planning a document explaining the new features. i have ADHD and dont pick up anything from videos, for me to learn it its gotta be text in my face lol.

thanks! :D

**Comment by ekirchman** [comment]
I agree with @Kazlehoff with the former statement - written guides are better. At least in the homebrew community, they much prefer written guides, as stuff can get outdated fast. And updating old videos isn't really an option, which leaves lots of outdated information out there on YouTube or other sites. But a written guide can be updated in a matter of minutes.

Furthermore, written guides can go into more technical detail, which can help technical users understand what the code is doing from a 1000 ft view before looking at it themselves.

**Comment by CryoByte33** [comment]
While I agree that written guides are more information-dense, I think that's their greatest weakness as well. If it wasn't, you'd be reading the kernel docs for all of those features instead of having them here 😉

The key is striking a balance, obviously, but this project just happened as a spin-off from my educational channel as mentioned before.

All that said, the guide will probably be a 100ft view with links to the kernel documents for fine-grain detail. I don't think it's very valuable to have a verbatim copy of them here, and they can definitely explain it best, technically speaking.
