### ISSUE TITLE
SMT disable 

### ISSUE THREAD

**Issue by Boricuaenluna** [CryoByte33/steam-deck-utilities#49]
I would love to have the capability to enable/disable SMT as part of your tool

**Comment by CryoByte33** [comment]
Is anyone else interested in this?

Some things to keep in mind:
* Disabling SMT couldn't be done per-game like it currently is with PowerTools
* The latest SteamOS version allegedly removes the need for disabling SMT [source](https://twitter.com/Plagman2/status/1626041563737645056)

**Comment by DavidDeSimone** [comment]
My personal recommendation would not be to have `steam-deck-utilities` allow enable/disable SMT - as you have said, powertools already handles that functionality on a per-game basis, and I would argue most people using this tool will also be familiar with powertools. 

A future point of expansion for  `steam-deck-utilities` could be recommending when to disable/enable SMT based on benchmarks and community observations, but that is kind of an orthogonal idea.

**Comment by CryoByte33** [comment]
I'll leave this open for a few days, if anyone else wants it please let me know here!

**Comment by bugworm** [comment]
Well, it depends on what direction this project is going. For now I see it as "tweaks to optimize/simplify stuff that SteamOS doesn't do well". SMT is double-edged sword, and it's easier to just use decky-loader with plugin to manage that stuff anyway, and if someone really need to disable SMT in desktop mode, he can just use a script to do that(it'll be easier to do that, actually). Complicating it to the point of having user reports and auto adjustments seems like different goal, so while it might work as a different project, I don't think SD-utilities should go this route.
