### ISSUE TITLE
Does not launch after recent update

### ISSUE THREAD

**Issue by gilest** [CryoByte33/steam-deck-utilities#53]
Followed the launcher script and found that the installed `cryo_utilities` binary is 0 bytes. No wonder it does nothing...

I saw a 404 in the update output, probably relevant.

Installer output:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3849  100  3849    0     0   8906      0 --:--:-- --:--:-- --:--:--  8909
--2023-02-22 20:45:32--  https://github.com/CryoByte33/steam-deck-utilities/releases/download/latest/cryoutilities
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving github.com (github.com)... 20.248.137.48
Connecting to github.com (github.com)|20.248.137.48|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-02-22 20:45:32 ERROR 404: Not Found.
```

I think there's a missing underscore in that url.

Yeah...

```
https://github.com/CryoByte33/steam-deck-utilities/releases/download/latest/cryoutilities
// 404
```

```
https://github.com/CryoByte33/steam-deck-utilities/releases/download/latest/cryo_utilities
// a binary
```

**Comment by walllable** [comment]
Ran into this just now as well.

**Comment by geberl** [comment]
Can confirm, caused by https://github.com/CryoByte33/steam-deck-utilities/commit/99f201e41c3c6789e76fa804401052bbe52d071b

**Comment by gilest** [comment]
If you're comfortable with the terminal you can fix by running

```sh
wget https://github.com/CryoByte33/steam-deck-utilities/releases/download/latest/cryo_utilities -O "$HOME/.cryo_utilities/cryo_utilities"
chmod +x "$HOME/.cryo_utilities/cryo_utilities"
```

**Comment by aihcho** [comment]
Haha I was just about to type this one up. You guys are quick!

**Comment by SyreeseOfficial** [comment]
> While you're waiting for an update you can fix by running
> 
> ```shell
> wget https://github.com/CryoByte33/steam-deck-utilities/releases/download/latest/cryo_utilities -O "$HOME/.cryo_utilities/cryo_utilities"
> chmod +x "$HOME/.cryo_utilities/cryo_utilities"
> ```

Hi, I'm new to linux. So do I just copy & paste that into a terminal and hit enter? Then try to relaunch the program? Thanks :)

**Comment by gilest** [comment]
> Hi, I'm new to linux. So do I just copy & paste that into a terminal and hit enter? Then try to relaunch the program? Thanks :)

That's right. Looks like the updater has been patched now though. You can probably just run that again to restore the app.

**Comment by CryoByte33** [comment]
This has been fixed, just run update again 🙂

**Comment by homersheineken** [comment]
I'm also getting this now where it won't start right after install. 

I tried running [SyreeseOfficial](https://github.com/SyreeseOfficial) wget.  

Also uninstalled and reinstalled.  

Update says no updates.
