### ISSUE TITLE
An error while setting a memory settings will close the main window

### ISSUE THREAD

**Issue by DavidDeSimone** [CryoByte33/steam-deck-utilities#69]
Steps to reproduce - force an error in the flow for setting huge pages (or any memory related setting). An artificial change to trigger this behavior in ui_tab.go would be:

``` golang
CryoUtils.HugePagesButton = widget.NewButton("Enable HugePages", func() {
		renewSudoAuth()
		err := ToggleHugePages()
		err = fmt.Errorf("Fake Error")
		if err != nil {
			presentErrorInUI(err, CryoUtils.MainWindow)
		}
		app.refreshHugePagesContent()
	})
```

This appears to be due to the following  function:

``` golang
func presentErrorInUI(err error, win fyne.Window) {
	CryoUtils.ErrorLog.Println(err)
	dialog.ShowError(err, CryoUtils.MainWindow)
	win.Close()
}
```

The issue is that win.Close() - it will close the main window. Removing that line will result in just displaying the error message to the user, so I think we just want to remove that function call to win.Close().

**Comment by CryoByte33** [comment]
This should be fixed, pending your merge. Thank you again for catching my mistake!
