### ISSUE TITLE
Default

### ISSUE THREAD

**Issue by SadKnight84** [CryoByte33/steam-deck-utilities#7]
Hello, what were the default settings?

**Comment by CryoByte33** [comment]
Heya, I'll update the README with them, but they're:
1GB Swap File
100 Swappiness
TRIM Disabled

After setting to those values, the Steam Deck will be entirely Stock again.

**Comment by SadKnight84** [comment]
thanks, with the new settings, it became impossible to play God of War

**Comment by CryoByte33** [comment]
Really? I've heard the opposite from 4 different viewers 🤔

**Comment by SadKnight84** [comment]
Yes, I did it

**Comment by CryoByte33** [comment]
Have you tried these fixes with VRAM still set to 1GB? I'm wondering if it has the same bug as RDR2 and I don't own the game, sorry 😅

**Comment by SadKnight84** [comment]
Yes, I did it too)) 
It's normal, no problem)

**Comment by CryoByte33** [comment]
Okay, so just to be clear:
These fixes with 4GB of VRAM - Bad performance
These fixes with 1GB of VRAM - Normal performance
No fixes with 4GB of VRAM - Bad performance
No fixes with 1GB of VRAM - Normal performance

Do I have that correct?

**Comment by SadKnight84** [comment]
Yes, which fps all good, but in some places the picture becomes grainy

**Comment by CryoByte33** [comment]
Yeah that makes sense because of dynamic resolution scaling. Thank you for all the help, I'll have to pay special attention to the 4GB of VRAM in the coming weeks to figure out if I should update my recommendations!

**Comment by SadKnight84** [comment]
Thanks
