### ISSUE TITLE
mitigations=off for extra CPU performance

### ISSUE THREAD

**Issue by mkazlouski** [CryoByte33/steam-deck-utilities#74]
There's a controversial topic of disabling Spectre / Meltdown mitigations to squeeze some extra CPU performance ([discussion](https://steamcommunity.com/app/1675200/discussions/0/5764050278020831337/)).

I was wondering whether you had a chance to investigate the benefit of such change to performance of CPU intensive games and emulators.

Thank you for your work btw!

**Comment by CryoByte33** [comment]
I already tested it in my Yuzu video and it had almost 0 performance difference 🙂

I'm reasonably sure that the latest AMD chips aren't nearly as affected by speculative mitigations as the previous generations, but if anyone else has competing evidence then I'd love to see it!

**Comment by mkazlouski** [comment]
All right, I would consider it a closed topic then. Thank you!
