### ISSUE TITLE
Success Story

### ISSUE THREAD

**Issue by jxbolt** [CryoByte33/steam-deck-utilities#8]
I am leaving a note to say this solved an issue I had with joining large maps in 7 Days to Die on my Steam Deck. Prior to this fix if I tried to join a 10k or larger map the game would crash just as the world should load. No errors could be found indicating what was causing the problem. 

I used the default setting suggested by the script and without restarting my deck I was able to join my server for the first time from the deck.

Impressive work and many thanks for sharing a clean solution with the community.

**Comment by CryoByte33** [comment]
Thank you for letting me know, I'm really happy that people are able to play their favorite games better than ever now! 😄
