### ISSUE TITLE
Sudo password is not validated between sessions if you have previously authenticated. 

### ISSUE THREAD

**Issue by DavidDeSimone** [CryoByte33/steam-deck-utilities#83]
Summary; If you run the app, authenticate, and relaunch the app (or otherwise are currently in a timing window where you are sudo authorized), and enter the incorrect password, you will get past the main screen asking for your your password. 

The reason appears to be that even though you are piping a password to sudo, since you are already authenticated, it doesn't check your password, and the command will pass. The issue is that `CryoUtils.UserPassword` will be incorrect, so if your authentication window expires and we attempt to re-auth, the app will provide the incorrect password to sudo for subsequent commands. 

I think we want to use the option `-k` for that first authentication to validated that what is entered is actually the users password.

**Comment by CryoByte33** [comment]
Sorry, should have put this here instead of the PR:
Is this not only a bug if you run CU from the terminal? I'm unable to replicate by just clicking the icon as it binds to a different session each time I click the icon.

**Comment by DavidDeSimone** [comment]
> Sorry, should have put this here instead of the PR:
> 
> Is this not only a bug if you run CU from the terminal? I'm unable to replicate by just clicking the icon as it binds to a different session each time I click the icon.

You are correct - I was launching CU from CLI in my iteration, which is how I ran into this.

**Comment by CryoByte33** [comment]
I don't think there's a caveat, but I'll need to test each "launch type" to test it 🙂

**Comment by DavidDeSimone** [comment]
Trying to fix this via “-k” had some unintended side affects in Cryos testing, so I’ll close this as a wontfix for now since this is a pretty specific situation that is pretty rare.
