### ISSUE TITLE
Installer not applying recommended settings

### ISSUE THREAD

**Issue by Kronos25** [CryoByte33/steam-deck-utilities#96]
Hi

I have tried to install CryoUtilities on my new steam deck (64 GB) and it stayed for more than 30m trying to setup the recommended configs, so I closed the installer and got a crash afterwards. I rebooted the  steamdeck, got on cryoutilities again and tried once more. However it instantly said it applied the recommended configs, but the swap size is not on 16 GB as it should (it's on 1). Everytime I try to move it manually it says "error in resizing" and applying the recommended settings doesn't seem to do anything.

I have uninstalled and reinstalled, tried to reset to stock but to no avail. What should I do?

**Comment by CryoByte33** [comment]
Hey, sorry you're having an issue!

It sounds like you really need to TRIM the drive and writes were really slow. Closing out early caused the swap file to be very broken. I'll need to add an "emergency swap recovery" feature, but in the meantime you can do this in Konsole:
```bash
cd /home
sudo swapoff -a
sudo dd if=/dev/zero of=swapfile bs=1G count=1
sudo chmod 600 swapfile
sudo mkswap swapfile
sudo swapon swapfile
```
This should put your swapfile back to the "original" state and allow you to run the tool again.

That said, before running the tool again, go to Game Mode > Settings > System> Run Storage Device Maintenance Tasks (near the bottom). It'll take a bit, but it'll run a TRIM on your drive and make it faster.

**Comment by Kronos25** [comment]
> Hey, sorry you're having an issue!
> 
> It sounds like you really need to TRIM the drive and writes were really slow. Closing out early caused the swap file to be very broken. I'll need to add an "emergency swap recovery" feature, but in the meantime you can do this in Konsole:
> 
> ```shell
> cd /home
> sudo swapoff -a
> sudo dd if=/dev/zero of=swapfile bs=1G count=1
> sudo chmod 600 swapfile
> sudo mkswap swapfile
> sudo swapon swapfile
> ```
> 
> This should put your swapfile back to the "original" state and allow you to run the tool again.
> 
> That said, before running the tool again, go to Game Mode > Settings > System> Run Storage Device Maintenance Tasks (near the bottom). It'll take a bit, but it'll run a TRIM on your drive and make it faster.

Worked like a charm! Thank you so much for the fast response and everything you do!!

**Comment by CryoByte33** [comment]
Awesome, I'll close this issue and open one for a "emergency recovery" for the swap file. Thank you for reporting the issue!
