### ISSUE TITLE
[Enhancement] Check if the app is already at the latest version before updating

### ISSUE THREAD

**Issue by gezawatt** [CryoByte33/steam-deck-utilities#98]
I love the app but I think it would be really cool if it could check if you're already running the latest version when you update, to avoid unnecessary downloads.

I'd try implementing it myself, I just don't know what would be the most elegant solution to this.

**Comment by CryoByte33** [comment]
I don't think there's a way to do it with the current release system, since it's always "latest". I could maybe do an md5sum and store it alongside the artifact, but that would still "launch" the installer, and just save on the binary download in the best case, I'm not sure if that's useful for you.

**Comment by gezawatt** [comment]
Can it check against the latest commit id?

**Comment by CryoByte33** [comment]
It would need to keep the last commit ID locally, which would make it a bit stateful. I plan to change the pipeline to only release tagged commits in the future, which could let me check a version, but I'd still need to persist the version locally. 

I think that storing the md5sum in the release makes the most sense upon further thought.
1. It would allow for checking if the current binary is up to date, regardless of release identifier.
2. It would allow for full statelessness
3. It would allow for validating that the binary download was successful and corruption-free, meaning we could add retry logic.

A little roundabout, but very good recommendation! I'll see about getting this functionality added in the coming week or so.

**Comment by gezawatt** [comment]
Thank you!! Sounds awesome

**Comment by CryoByte33** [comment]
@gezawatt Done, the installer is now smart!

- It'll only download a new binary if there's actually an update
- It'll try to download the binary 3 times
- If it can't verify that the binary is perfect, then it'll actually say it failed

I'd appreciate it if you could test and let me know if it meets your needs 🙂

**Comment by gezawatt** [comment]
@CryoByte33 I just tested this, and it works amazingly!!
I even tested cancelling the download, and it also works, stopping the script from proceeding further (Although you have to cancel 3 times)

But yeah, the installer is definitely a lot smarter now, tysm!

**Comment by CryoByte33** [comment]
Awesome, thank you for letting me know 🙂

> Although you have to cancel 3 times

I haven't found a way to completely break out in this case yet, because the zenity UI is being piped into. I'll look into a way in the future, but I think this is adequate for now.

I'll close the issue since the main bit is resolved.

**Comment by gezawatt** [comment]
Tysm again
