### ISSUE TITLE
Cannot change SWAP size

### ISSUE THREAD

**Issue by londiebrondie** [CryoByte33/steam-deck-utilities#99]
It gives me the same error every time. And yes, I've tried going into game mode and running a storage device maintenance task, that didn't fix the error. I've also tried restarting my steam deck and uninstalling and reinstalling the app.
![image](https://user-images.githubusercontent.com/125153020/222779506-e2295439-a16b-48ff-9a6a-c3d17ced9fe6.png)
![image](https://user-images.githubusercontent.com/125153020/222779546-c0d4c8d5-694f-425c-be7e-932b88a19a9b.png)
![image](https://user-images.githubusercontent.com/125153020/222779581-d42e9f9d-21e9-4e8a-b2ab-06971261ec4b.png)

**Comment by CryoByte33** [comment]
Is this a on Steam Deck, or other Linux system? Did you cancel a running resize/recommended settings application before?

**Comment by Andolion** [comment]
Can confirm, this also happened on my Steam Deck. Restarting does not work, trim does not work. I would also like to point out that it seems the utility is unable to even recognize the size of the swap file. I have used this utility before(an older version) to change my swap file size to 16gb and it worked. To your question @CryoByte33, I did not cancel any running rezise/recommended settings application, but it might be that because it is unable to read the swap file size it gives an internal error somewhere that causes the issues.

**Comment by CryoByte33** [comment]
@Andolion Can you see if your swapfile is listed by running the command `swapon -s`?

**Comment by jalanimal** [comment]
I am having this same issue and have tried those solutions with no success as well

**Comment by CryoByte33** [comment]
@jalanimal Same question as above, anything in `swapon -s`? Also, are you using a Steam Deck?

**Comment by jalanimal** [comment]
> 

I’m using a deck yes. Do I just do put and paste that command on my konsole? Sorry, pretty new to this

**Comment by CryoByte33** [comment]
Yeah, just put that in konsole and run it. It should come back with your swapfile, if not then that's the issue.

**Comment by CryoByte33** [comment]
Alright, so then this will be fixed by #97 as soon as it's implemented. In the meantime do the steps in #96, my first comment. Sorry that you're having the issue, it seems like there are more people out there with broken swaps that I thought 😅

**Comment by jalanimal** [comment]
> Alright, so then this will be fixed by #97 as soon as it's implemented. In the meantime do the steps in #96, my first comment. Sorry that you're having the issue, it seems like there are more people out there with broken swaps that I thought 😅

That worked! Thank you so much! Have a great weekend and thank you for all the work you’re doing

**Comment by CryoByte33** [comment]
This should now be resolved with the merge of #100.

Please confirm that the latest version doesn't have the same issue and let me know if it works!

**Comment by Andolion** [comment]
Can confirm, new version worked. Kyle, you're a god damn wizand mate.

**Comment by CryoByte33** [comment]
> Kyle, you're a god damn wizard mate.

I can't be a wizard, I'm just Kyle!

But for real, thank you for testing! I'll close this issue, but if anyone else has it with the new version please re-open!

**Comment by VexelSoftware** [comment]
This issue appears to have returned in the latest Steam OS 3.7 preview release today.  It cannot detect the size of the swap file (it shows unknown), or change it (it results in the "Error resizing" warning).  I had to use the manual console commands to reset the swap file to 1GB.

**Comment by CryoByte33** [comment]
Does this happen only after updating to the new OS version with swap already resized, or even if you had the default swap file prior to upgrading?

**Comment by VexelSoftware** [comment]
> Does this happen only after updating to the new OS version with swap already resized, or even if you had the default swap file prior to upgrading?

Thank you for the prompt reply!

In my case it happened when I updated the OS with a pre-existing 24GB swap file setup using Cryutilities.  I was able to resize back to 1GB using the console commands you recommended in an earlier post, run maintenance and then power cycle the Deck. However when trying to resize with Cryutilities after resetting the swap file size it still fails to see the file or its size and encounters an error when attempting to resize with the tool.

I'm happy to run any tests you need on this end.
